### ISSUE TITLE
setup.py: namespace_packages is setuptools option (while using distutils)

### ISSUE THREAD

**Issue by mgorny** [peterjc/backports.lzma#28]
The setup.py script uses plain `distutils`. However, it passes:

      namespace_packages = ['backports'],

This is an option specific to `setuptools` and it does not do anything in `distutils`, as `setup.py` warns:

    /usr/lib64/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'namespace_packages'
      warnings.warn(msg)

**Comment by peterjc** [comment]
I noticed (and ignored) the warning while doing the 0.0.9 release (the release process has changed due to PyPI updated, eg using twisted for the upload).

I've moved other projects from distutils to setuptools, but given ``backports.lzma`` is a backport, do you think it is OK to require setuptools as a dependency?

**Comment by mgorny** [comment]
Well, `namespace_packages` is not correct here anyway since top [backports](https://pypi.python.org/pypi/backports) module uses pkgutil-style namespace (so you should use that one too as mixing different kinds of namespaces between packages using `backports.*` can cause mayhem).

But as a generic question, I suppose at this point `setuptools` are so common that there's no point in avoiding it.

**Comment by abadger** [comment]
Please no, can't we just move to using pkgutil-style namespaces?  Otherwise your one package will be responsible for breaking all the other backports packages out there.  (For instance, my colleague just spent the morning tracing this build failure: https://app.shippable.com/github/ansible/ansible/runs/51657/31/tests  back to this package causing problems for backports.ssl_match_hostname)

**Comment by mattclay** [comment]
From the [building your own backports module](https://pypi.python.org/pypi/backports) instructions:

The one __absolutely essential rule__ is that the \_\_init\_\_.py inside of the backports directory itself __must__ have the following code as its content:

```python
# A Python "namespace package" http://www.python.org/dev/peps/pep-0382/
# This always goes inside of a namespace package's __init__.py

from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```

If you fail to include this code, then the namespace package might fail to see all of the packages beneath it, and import statements might return errors.

**Comment by abadger** [comment]
@mgorny @peterjc Here's a PR to fix this: https://github.com/peterjc/backports.lzma/pull/32  See if that works for you.

I took a look at the previous PRs and issues that lead up to this point.  The tldr; version is that the code was originally correct.

The longer explanation is that setuptools was issuing a warning about that code but setuptools has since been fixed.  The warning can still be seen on distros that use very old setuptools (RHEL6 has setuptools-0.6.10, for instance) but current setuptools does not print a warning.  The warning would only be seen when using a backports module in conjunction with pkg_resources at runtime.  The warning was harmless in this case (setuptools was not being smart enough about understanding the paths.)
